routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('dashboard');

Route::group(['middleware' => 'auth'], function(){
    Route::resource('prodi','Admin\ProdiController');
    Route::resource('kurikulum','Admin\KurikulumController');
    Route::resource('fakultas','Admin\FakultasController');
    Route::resource('periode','Admin\PeriodeController');
    Route::resource('matakuliah','Admin\MatakuliahController');
    Route::resource('mk-kurikulum','Admin\MatakuliahKurikulumController');
    Route::resource('user','Admin\UserController');
    Route::resource('data-formulir','Admin\DataFormulirController');
    Route::resource('pegawai','Admin\PegawaiController');
    Route::resource('jabatan','Admin\JabatanController');
    Route::resource('jabatan-pegawai','Admin\JabatanPegawaiController');
    Route::resource('pendidik','Admin\PendidikController');
    Route::resource('calon-mahasiswa','Admin\CalonMahasiswaController');
    Route::resource('gol-matakuliah','Admin\GolMatakuliahController');
    Route::resource('status-pegawai','Admin\StatusPegawaiController');
    Route::resource('status-mahasiswa','Admin\StatusMahasiswaController');
    Route::resource('mahasiswa','Admin\MahasiswaController');

    Route::post('archived-faculty','Admin\FakultasController@archiveFaculty')->name('archiveFaculty');
    Route::post('archived-kurikulum','Admin\KurikulumController@archiveKurikulum')->name('archiveKurikulum');
    Route::post('archived-matakuliah','Admin\MatakuliahController@archiveMatakuliah')->name('archiveMatakuliah');
    Route::post('archived-prodi','Admin\ProdiController@archiveProdi')->name('archiveProdi');
    Route::post('archived-data-formulir','Admin\DataFormulirController@archiveDataFormulir')->name('archiveDataFormulir');
    Route::post('archived-jabatan-pegawai','Admin\JabatanPegawaiController@archiveJabatanPegawai')->name('archiveJabatanPegawai');
    Route::post('archived-status-pegawai','Admin\StatusPegawaiController@archiveStatusPegawai')->name('archiveStatusPegawai');
    Route::post('archived-status-mahasiswa','Admin\StatusMahasiswaController@archiveStatusMahasiswa')->name('archiveStatusMahasiswa');

    Route::post('switch-period','Admin\PeriodeController@switchPeriode')->name('change-period-status');
    Route::post('switch-matakuliah','Admin\MatakuliahController@switchMatakuliah')->name('change-matakuliah-status');
    Route::post('switch-kurikulum','Admin\KurikulumController@switchKurikulum')->name('change-kurikulum-status');
    Route::get('matakuliah-view','Admin\MatakuliahController@view')->name('view-detail-matakuliah');
    Route::get('profile','Admin\UserController@profile')->name('profile');

    Route::get('change-password', 'Admin\UserController@getPass');
    Route::post('change-password', 'Admin\UserController@postPass')->name('change-password');

    Route::get('/add-matakuliah-kurikulum/{id}','Admin\MatakuliahKurikulumController@index')->name('setting.mkkurikulum');
    Route::get('/add-matakuliah-kurikulums/{id}','Admin\MatakuliahKurikulumController@listMK')->name('list.mkkurikulum');
    Route::delete('/del-matakuliah-kurikulum/{id}','Admin\MatakuliahKurikulumController@destroy')->name('del.mkkurikulum');

    Route::get('show-archived-matakuliah','Admin\MatakuliahController@show')->name('show.archived.matakuliah');
    Route::get('show-archived-kurikulum','Admin\KurikulumController@show')->name('show.archived.kurikulum');
    Route::get('show-archived-fakultas','Admin\FakultasController@show')->name('show.archived.fakultas');
    Route::get('show-archived-prodi','Admin\ProdiController@show')->name('show.archived.prodi');
    Route::get('show-archived-data-formulir','Admin\DataFormulirController@show')->name('show.archived.dataformulir');
    Route::get('show-archived-jabatan-pegawai','Admin\JabatanPegawaiController@show')->name('show.archived.jabatanpegawai');
    Route::get('show-archived-status-pegawai','Admin\StatusPegawaiController@show')->name('show.archived.status.pegawai');
    Route::get('show-archived-status-mahasiswa','Admin\StatusMahasiswaController@show')->name('show.archived.status.mahasiswa');
    
    Route::post('unarchived-matakuliah','Admin\MatakuliahController@unarchiveMatakuliah')->name('unarchiveMatakuliah');
    Route::post('unarchived-kurikulum','Admin\KurikulumController@unarchiveKurikulum')->name('unarchiveKurikulum');
    Route::post('unarchived-fakultas','Admin\FakultasController@unarchiveFakultas')->name('unarchiveFakultas');
    Route::post('unarchived-prodi','Admin\ProdiController@unarchiveProdi')->name('unarchiveProdi');
    Route::post('unarchived-data-formulir','Admin\DataFormulirController@unarchiveDataFormulir')->name('unarchiveDataFormulir');
    Route::post('unarchived-jabatan-pegawai','Admin\JabatanPegawaiController@unarchiveJabatanPegawai')->name('unarchiveJabatanPegawai');
    Route::post('unarchived-status-pegawai','Admin\StatusPegawaiController@unarchiveStatusPegawai')->name('unarchiveStatusPegawai');
    Route::post('unarchived-status-mahasiswa','Admin\StatusMahasiswaController@unarchiveStatusMahasiswa')->name('unarchiveStatusMahasiswa');

    Route::get('mahasiswa-view','Admin\CalonMahasiswaController@view')->name('view-detail-mahasiswa');

    // API Mahasiswa
    Route::get('/mahasiswa/tahun','Admin\CalonMahasiswaController@show')->name('get.mahasiswa');
    Route::get('mahasiswa-view','Admin\CalonMahasiswaController@view')->name('view-detail-mahasiswa');
    Route::get('datatable-mahasiswa','Admin\CalonMahasiswaController@showDataTable')->name('datatable-mahasiswa');
    
    Route::resource('api-mahasiswa', 'Admin\ApiMahasiswaController');
    Route::get('api-mahasiswa-view','Admin\ApiMahasiswaController@viewformdetail')->name('view-detail-form');
    Route::resource('api-mahasiswa-prodi', 'Admin\ApiMahasiswaProdiController');
    Route::get('datatable-mahasiswa-prodi','Admin\ApiMahasiswaProdiController@showDataTable')->name('datatable-mahasiswa-prodi');

    // Keuangan
    Route::resource('payment-list','Keuangan\PaymentListController');
    Route::resource('payment','Keuangan\PaymentController');
    Route::get('/view-rincian-payment/{id}','Keuangan\ViewRincianPaymentController@index')->name('view-rincian-payment');
    Route::get('/rincian-payment/{id}','Keuangan\ViewRincianPaymentController@index')->name('list-rincian-payment');
    Route::get('/view-rincian-payment/payment/{id}/edit','Keuangan\PaymentController@edit');
    Route::delete('/view-rincian-payment/payment/{id}','Keuangan\PaymentController@destroy');

    Route::get('print-payment','Keuangan\PaymentController@print')->name('print-payment');
    Route::post('add-potongan','Keuangan\ViewRincianPaymentController@addPotongan')->name('add-potongan');

    Route::post('import-payment', 'Keuangan\PaymentController@importPayment')->name('import-payment');
    Route::get('count-fine','Keuangan\PaymentController@countFine')->name('count-fine');

    Route::resource('setup-biaya','Keuangan\SetupBiayaController');
    Route::resource('biaya-kuliah','Keuangan\BiayaKuliahController');

    Route::resource('custom-biaya','Keuangan\CustomBiayaController');
    Route::post('switch-custom-biaya','Keuangan\CustomBiayaController@switchStatus')->name('change-custom-biaya-status');

    Route::resource('discount-biaya','Keuangan\DiscountBiayaController');
    Route::get('/potongan-biaya/{id}','Keuangan\DiscountBiayaController@index')->name('potongan-biaya');
    Route::get('/list-discounts/{id}','Keuangan\DiscountBiayaController@listDiscount')->name('list-discount');
    Route::delete('/del-list-discount/{id}','Keuangan\DiscountBiayaController@destroy')->name('del-discount');
    Route::post('import-biaya-kuliah', 'Keuangan\BiayaKuliahController@importBiayaKuliah')->name('import-biaya-kuliah');
    
    Route::post('search-payment-history', 'Keuangan\ViewRincianPaymentController@searchPaymentHistory')->name('search-payment-history');
    
    Route::resource('fines','Keuangan\FineController');
    Route::resource('invoice','Keuangan\InvoiceController');
    Route::post('import-invoice', 'Keuangan\InvoiceController@importInvoice')->name('import-invoice');

    Route::resource('g-biaya-kuliah','Keuangan\GroupBiayaKuliahController');
    
    Route::resource('detail-biaya-kuliah','Keuangan\DetailBiayaKuliahController');
    Route::get('/set-detail-biaya/{id}','Keuangan\DetailBiayaKuliahController@index')->name('set-detail-biaya');
    Route::get('/list-details/{id}','Keuangan\DetailBiayaKuliahController@listDetail')->name('list-detail');
    Route::delete('/del-list-detail/{id}','Keuangan\DetailBiayaKuliahController@destroy')->name('del-detail');

    // Perkuliahan
    Route::resource('gol-kelas','Perkuliahan\GolKelasController');
    Route::resource('in-kelas','Perkuliahan\InKelasController');
    Route::get('/add-kelas/{id}','Perkuliahan\InKelasController@index')->name('in.kelas');
    Route::get('/add-kelas-mhs/{id}','Perkuliahan\InKelasController@listMahasiswa')->name('list.mahasiswa');
    Route::delete('/del-kelas-mhs/{id}','Perkuliahan\InKelasController@destroy')->name('del.mahasiswa');

    Route::resource('status-kelas-kuliah','Perkuliahan\StatusKelasKuliahController');
    Route::resource('karakter-matakuliah','Perkuliahan\KarakterMatakuliahController');
    Route::resource('buka-kelas','Perkuliahan\BukaKelasController');
});

app/Http/Controllers/Admin/CalonMahasiswaController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Mahasiswa;
use App\Model\Periode;
use Response;
use Session;
use Validator;
use Auth;

class CalonMahasiswaController extends Controller
{
    public function index(Request $request)
    {

        // Just for TahunAjaran
        $getApiTahunAjaran = file_get_contents('put-your-url-here/api/tahun-ajaran');
        $jsonTahunAjaran = json_decode($getApiTahunAjaran, TRUE);

        return view('administrator.calon-mahasiswa.index', compact('jsonTahunAjaran'));
    }

    public function show(Request $request)
    {
        if($request->tahun){
            $getApi = 'put-your-url-here/api/data-mahasiswa/'.$request->tahun;
            $datas = file_get_contents($getApi);
            $json = json_decode($datas, TRUE);
        }else{
            $getApi = 'put-your-url-here/api/data-mahasiswa';
            $datas = file_get_contents($getApi);
            $json = json_decode($datas, TRUE);
        }
        if($request->ajax()){
            return datatables()->of($json)
                ->addColumn('action', function($data){
                        $button = '<button type="button" name="view_detail" id="'.$data['kode_registrasi'].'" class="view_detail btn btn-info btn-xs" data-toggle="tooltip" data-placement="bottom" title="View Details"><i class="bx bx-xs bx-show"></i></button>';
                        $button .= '&nbsp;&nbsp;';
                        $button .= '<a href="javascript:void(0)" data-toggle="tooltip" data-id="'.$data['kode_registrasi'].'" data-toggle="tooltip" data-placement="bottom" title="Edit" data-original-title="Edit" class="edit btn btn-success btn-xs edit-post"><i class="bx bx-xs bx-edit"></i></a>';
                        $button .= '&nbsp;&nbsp;';
                        $button .= '<button type="button" name="delete" id="'.$data['kode_registrasi'].'" data-toggle="tooltip" data-placement="bottom" title="Delete" class="delete btn btn-danger btn-xs"><i class="bx bx-xs bx-trash"></i></button>';
                        return $button;
                })
                ->rawColumns(['action'])
                ->addIndexColumn(true)
                ->make(true);
        }

        return view('administrator.calon-mahasiswa.index');
    }

    protected function view(Request $request)
    {
        $getApi = 'put-your-url-here/api/detail-form-mahasiswa/'.$request->dataId;
        $datas = file_get_contents($getApi);
        $json = json_decode($datas, TRUE);
        $rows = array();

        foreach($json as $no => $data){
            $content = '<table class="table table-borderless table-sm">
                <tbody>
                    <tr><td>'.$data[39]['nama_data'].'</td><td>:</td><td>'.$data[39]['isi_data'].'</td></tr>
                    <tr><td>No Form</td><td>:</td><td>'.$data[0]['kode_registrasi'].'</td></tr>
                    <tr><td>Prodi</td><td>:</td><td>'.$data[0]['nama_prodi'].'</td></tr>
                    <tr><td>Angkatan</td><td>:</td><td>'.$data[0]['tahun'].'</td></tr>
                    <tr><td>'.$data[29]['nama_data'].'</td><td>:</td><td>'.$data[29]['isi_data'].'</td></tr>
                    <tr><td>Tempat, tanggal lahir</td><td>:</td><td>'.$data[30]['isi_data'].', '.$data[31]['isi_data'].'</td></tr>
                    <tr><td>'.$data[32]['nama_data'].'</td><td>:</td><td>'.$data[32]['isi_data'].'</td></tr>
                    <tr><td>'.$data[38]['nama_data'].'</td><td>:</td><td>'.$data[38]['isi_data'].'</td></tr>
                </tbody>
            </table>';
        }    

        return response()->json(['table' => $content]);

    }

    protected function showDataTable(Request $request)
    {
        $getApi = 'put-your-url-here/api/data-mahasiswa/'.$request->yearSelect;
        $datas = file_get_contents($getApi);
        $json = json_decode($datas, TRUE);
        $rows = array();
        $no = 1;
        $nim = 1;

        
            $contents = '<div class="card-body">
                        <table id="datatable-mahasiswa" class="table table-hover table-responsive">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>NIM Generated</th>
                                <th>Kode Registrasi</th>
                                <th>Nama Lengkap</th>
                                <th>Prodi</th>
                                <th>Action</th>                
                            </tr>
                        </thead>
                        <tbody>';
            if(!empty($json)){
            foreach($json as $data){
            $contents .= '
                            <tr>
                                <td>'.$no++.'</td>
                                <td><span class="badge bg-label-primary me-1">'.$data[0]['tahun'].' . '.$data[0]['kode_nim'].' . '. sprintf('%03d', $nim++).'</span></td>
                                <td>'.$data[0]['kode_registrasi'].'</td>
                                <td>'.$data[0]['nama_lengkap'].'</td>
                                <td>'.$data[0]['prodi_fix'].'</td>
                                <td>
                                    <button type="button" name="view_detail" id="'.$data[0]['kode_registrasi'].'" class="view_detail btn btn-info btn-xs" data-toggle="tooltip" data-placement="bottom" title="View Details"><i class="bx bx-xs bx-show"></i></button>&nbsp;&nbsp;
                                    <a href="javascript:void(0)" data-toggle="tooltip" data-id="'.$data[0]['kode_registrasi'].'" data-toggle="tooltip" data-placement="bottom" title="Edit" data-original-title="Edit" class="edit btn btn-success btn-xs edit-post"><i class="bx bx-xs bx-edit"></i></a>&nbsp;&nbsp;
                                    <button type="button" name="delete" id="'.$data[0]['kode_registrasi'].'" data-toggle="tooltip" data-placement="bottom" title="Delete" class="delete btn btn-danger btn-xs"><i class="bx bx-xs bx-trash"></i></button>
                                </td>
                            </tr>';
            }} else {
            $contents .= '
                            <tr>
                                <td colspan="12" align="center">No data available in table</td>
                            </tr>
            ';
            }
            $contents .= '</tbody>
                        </table>
                        </div>';   

        return response()->json(['dataTable' => $contents]);
    }

    public function edit($id)
    {
        $where = array('id' => $id);
        $post  = Mahasiswa::where($where)->first();
     
        return response()->json($post);
    }
}

resources/views/administrator/calon-mahasiswa/index.blade.php
@extends('layouts.backend')
@section('title','Mahasiswa')

@section('breadcrumbs')
<div class="container">
<nav aria-label="breadcrumb mb-0">
    <ol class="breadcrumb breadcrumb-style2">
      <li class="breadcrumb-item">
        <a href="{{route('dashboard')}}">Home</a>
      </li>
      <li class="breadcrumb-item">
        <a href="{{route('calon-mahasiswa.index')}}">@yield('title')</a>
      </li>
      <li class="breadcrumb-item active">Data</li>
    </ol>
</nav>
</div>
@endsection

@section('content')

<div class="container flex-grow-1">
    <section id="basic-datatable">
        <div class="row mt-3">
            <div class="col-sm-12 mb-3">
                <form class="row g-3" id="form-show" name="form-show">
                    @csrf
                    <div class="col-auto">
                        <label for="inputTahun" class="col-sm-12 col-form-label">Tahun Ajaran</label>
                    </div>
                    <div class="col-auto">
                      <select style="cursor:pointer;" class="form-control" id="tahun" name="tahun" required>
                            <option value="" readonly> - Pilih Tahun -</option>
                                @foreach($jsonTahunAjaran as $key => $data)
                                <option value="{{$data['tahun']}}">{{$data['tahun']}}</option>
                                @endforeach
                            <span class="tahunErrorMsg"></span>
                        </select>
                    </div>
                    <div class="col-auto">
                        <button class="btn btn-primary" id="tombol-show" name="submit" type="submit">Show datas</button>
                    </div>
                    <div class="col-sm">
                        <a href="{{route('api-mahasiswa.index')}}" class="dropdown-shortcuts-add text-body float-end" data-bs-toggle="tooltip" data-bs-placement="top" title="Back to All Mahasiswa"><i class="bx bx-xs bx-left-arrow-circle bx-tada-hover"></i> Kembali</a>
                    </div>
                </form>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
                <div class="card" id="datatable-mahasiswa">
                    
                </div>

                <!-- MULAI MODAL VIEW DETAIL-->
                <div class="modal fade" tabindex="-1" role="dialog" id="view_detail" data-backdrop="false">
                    <div class="modal-dialog" role="document">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title">Details</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                            </div>
                            <div class="modal-body">
                                <div id="table" class="col-sm-12 table-responsive"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- AKHIR MODAL VIEW DETAIL-->
            </div>
        </div>
    </section>
</div>

@endsection
@section('script')

<script>
    $(document).ready(function () {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
    });

    // SEARCH
    if ($("#form-show").length > 0) {
        $("#form-show").validate({
            submitHandler: function (form) {
                var actionType = $('#tombol-show').val();
                yearSelect = document.getElementById("tahun").value;
                $('#tombol-show').html('Processing..');
                $.ajax({
                    url: '{{ route("datatable-mahasiswa") }}',
                    data: {yearSelect:yearSelect},
                    type: "GET",
                    dataType: 'json',
                    success: function(response, data){
                        $("#datatable-mahasiswa").html(response.dataTable);
                        $('#tombol-show').html('Show datas');
                    },
                    error: function(response) {
                        console.log('Failed to get datas of '+yearSelect);
                        $('#tombol-show').html('Show datas');
                    }
                });
            }
        })
    }

    // TOMBOL VIEW
    $(document).on('click', '.view_detail', function () {
        dataId = $(this).attr('id');
        $.ajax({
			url: "{{route('view-detail-mahasiswa')}}",
			method: "GET",
			data: {dataId: dataId},
			success: function(response, data){
                $('#view_detail').modal('show');
                $("#table").html(response.table)
			}
		})
    });

    // EDIT DATA
    $('body').on('click', '.edit-post', function () {
        var data_id = $(this).data('id');
        alert(data_id);
        $.get('calon-mahasiswa/' + data_id + '/edit', function (data) {
            $('#modal-judul').html("Edit data");
            $('#tombol-simpan').val("edit-post");
            $('#tambah-edit-modal').modal('show');
              
            $('#id').val(data.id);
            $('#nama_data').val(data.nama_data);
            $('#isi_data').val(data.isi_data);
            $('#no_hp').val(data.no_hp);
            $('#nama_prodi').val(data.nama_prodi);
        })
    });

</script>

@endsection