routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('dashboard');

Route::group(['middleware' => 'auth'], function(){
    Route::resource('prodi','Admin\ProdiController');
    Route::resource('kurikulum','Admin\KurikulumController');
    Route::resource('fakultas','Admin\FakultasController');
    Route::resource('periode','Admin\PeriodeController');
    Route::resource('matakuliah','Admin\MatakuliahController');
    Route::resource('mk-kurikulum','Admin\MatakuliahKurikulumController');
    Route::resource('user','Admin\UserController');
    Route::resource('data-formulir','Admin\DataFormulirController');
    Route::resource('pegawai','Admin\PegawaiController');
    Route::resource('jabatan','Admin\JabatanController');
    Route::resource('jabatan-pegawai','Admin\JabatanPegawaiController');
    Route::resource('pendidik','Admin\PendidikController');
    Route::resource('calon-mahasiswa','Admin\CalonMahasiswaController');
    Route::resource('gol-matakuliah','Admin\GolMatakuliahController');
    Route::resource('status-pegawai','Admin\StatusPegawaiController');
    Route::resource('status-mahasiswa','Admin\StatusMahasiswaController');
    Route::resource('mahasiswa','Admin\MahasiswaController');

    Route::post('archived-faculty','Admin\FakultasController@archiveFaculty')->name('archiveFaculty');
    Route::post('archived-kurikulum','Admin\KurikulumController@archiveKurikulum')->name('archiveKurikulum');
    Route::post('archived-matakuliah','Admin\MatakuliahController@archiveMatakuliah')->name('archiveMatakuliah');
    Route::post('archived-prodi','Admin\ProdiController@archiveProdi')->name('archiveProdi');
    Route::post('archived-data-formulir','Admin\DataFormulirController@archiveDataFormulir')->name('archiveDataFormulir');
    Route::post('archived-jabatan-pegawai','Admin\JabatanPegawaiController@archiveJabatanPegawai')->name('archiveJabatanPegawai');
    Route::post('archived-status-pegawai','Admin\StatusPegawaiController@archiveStatusPegawai')->name('archiveStatusPegawai');
    Route::post('archived-status-mahasiswa','Admin\StatusMahasiswaController@archiveStatusMahasiswa')->name('archiveStatusMahasiswa');

    Route::post('switch-period','Admin\PeriodeController@switchPeriode')->name('change-period-status');
    Route::post('switch-matakuliah','Admin\MatakuliahController@switchMatakuliah')->name('change-matakuliah-status');
    Route::post('switch-kurikulum','Admin\KurikulumController@switchKurikulum')->name('change-kurikulum-status');
    Route::get('matakuliah-view','Admin\MatakuliahController@view')->name('view-detail-matakuliah');
    Route::get('profile','Admin\UserController@profile')->name('profile');

    Route::get('change-password', 'Admin\UserController@getPass');
    Route::post('change-password', 'Admin\UserController@postPass')->name('change-password');

    Route::get('/add-matakuliah-kurikulum/{id}','Admin\MatakuliahKurikulumController@index')->name('setting.mkkurikulum');
    Route::get('/add-matakuliah-kurikulums/{id}','Admin\MatakuliahKurikulumController@listMK')->name('list.mkkurikulum');
    Route::delete('/del-matakuliah-kurikulum/{id}','Admin\MatakuliahKurikulumController@destroy')->name('del.mkkurikulum');

    Route::get('show-archived-matakuliah','Admin\MatakuliahController@show')->name('show.archived.matakuliah');
    Route::get('show-archived-kurikulum','Admin\KurikulumController@show')->name('show.archived.kurikulum');
    Route::get('show-archived-fakultas','Admin\FakultasController@show')->name('show.archived.fakultas');
    Route::get('show-archived-prodi','Admin\ProdiController@show')->name('show.archived.prodi');
    Route::get('show-archived-data-formulir','Admin\DataFormulirController@show')->name('show.archived.dataformulir');
    Route::get('show-archived-jabatan-pegawai','Admin\JabatanPegawaiController@show')->name('show.archived.jabatanpegawai');
    Route::get('show-archived-status-pegawai','Admin\StatusPegawaiController@show')->name('show.archived.status.pegawai');
    Route::get('show-archived-status-mahasiswa','Admin\StatusMahasiswaController@show')->name('show.archived.status.mahasiswa');
    
    Route::post('unarchived-matakuliah','Admin\MatakuliahController@unarchiveMatakuliah')->name('unarchiveMatakuliah');
    Route::post('unarchived-kurikulum','Admin\KurikulumController@unarchiveKurikulum')->name('unarchiveKurikulum');
    Route::post('unarchived-fakultas','Admin\FakultasController@unarchiveFakultas')->name('unarchiveFakultas');
    Route::post('unarchived-prodi','Admin\ProdiController@unarchiveProdi')->name('unarchiveProdi');
    Route::post('unarchived-data-formulir','Admin\DataFormulirController@unarchiveDataFormulir')->name('unarchiveDataFormulir');
    Route::post('unarchived-jabatan-pegawai','Admin\JabatanPegawaiController@unarchiveJabatanPegawai')->name('unarchiveJabatanPegawai');
    Route::post('unarchived-status-pegawai','Admin\StatusPegawaiController@unarchiveStatusPegawai')->name('unarchiveStatusPegawai');
    Route::post('unarchived-status-mahasiswa','Admin\StatusMahasiswaController@unarchiveStatusMahasiswa')->name('unarchiveStatusMahasiswa');

    Route::get('mahasiswa-view','Admin\CalonMahasiswaController@view')->name('view-detail-mahasiswa');

    // API Mahasiswa
    Route::get('/mahasiswa/tahun','Admin\CalonMahasiswaController@show')->name('get.mahasiswa');
    Route::get('mahasiswa-view','Admin\CalonMahasiswaController@view')->name('view-detail-mahasiswa');
    Route::get('datatable-mahasiswa','Admin\CalonMahasiswaController@showDataTable')->name('datatable-mahasiswa');
    
    Route::resource('api-mahasiswa', 'Admin\ApiMahasiswaController');
    Route::get('api-mahasiswa-view','Admin\ApiMahasiswaController@viewformdetail')->name('view-detail-form');
    Route::resource('api-mahasiswa-prodi', 'Admin\ApiMahasiswaProdiController');
    Route::get('datatable-mahasiswa-prodi','Admin\ApiMahasiswaProdiController@showDataTable')->name('datatable-mahasiswa-prodi');

    // Keuangan
    Route::resource('payment-list','Keuangan\PaymentListController');
    Route::resource('payment','Keuangan\PaymentController');
    Route::get('/view-rincian-payment/{id}','Keuangan\ViewRincianPaymentController@index')->name('view-rincian-payment');
    Route::get('/rincian-payment/{id}','Keuangan\ViewRincianPaymentController@index')->name('list-rincian-payment');
    Route::get('/view-rincian-payment/payment/{id}/edit','Keuangan\PaymentController@edit');
    Route::delete('/view-rincian-payment/payment/{id}','Keuangan\PaymentController@destroy');

    Route::get('print-payment','Keuangan\PaymentController@print')->name('print-payment');
    Route::post('add-potongan','Keuangan\ViewRincianPaymentController@addPotongan')->name('add-potongan');

    Route::post('import-payment', 'Keuangan\PaymentController@importPayment')->name('import-payment');
    Route::get('count-fine','Keuangan\PaymentController@countFine')->name('count-fine');

    Route::resource('setup-biaya','Keuangan\SetupBiayaController');
    Route::resource('biaya-kuliah','Keuangan\BiayaKuliahController');

    Route::resource('custom-biaya','Keuangan\CustomBiayaController');
    Route::post('switch-custom-biaya','Keuangan\CustomBiayaController@switchStatus')->name('change-custom-biaya-status');

    Route::resource('discount-biaya','Keuangan\DiscountBiayaController');
    Route::get('/potongan-biaya/{id}','Keuangan\DiscountBiayaController@index')->name('potongan-biaya');
    Route::get('/list-discounts/{id}','Keuangan\DiscountBiayaController@listDiscount')->name('list-discount');
    Route::delete('/del-list-discount/{id}','Keuangan\DiscountBiayaController@destroy')->name('del-discount');
    Route::post('import-biaya-kuliah', 'Keuangan\BiayaKuliahController@importBiayaKuliah')->name('import-biaya-kuliah');
    
    Route::post('search-payment-history', 'Keuangan\ViewRincianPaymentController@searchPaymentHistory')->name('search-payment-history');
    
    Route::resource('fines','Keuangan\FineController');
    Route::resource('invoice','Keuangan\InvoiceController');
    Route::post('import-invoice', 'Keuangan\InvoiceController@importInvoice')->name('import-invoice');

    Route::resource('g-biaya-kuliah','Keuangan\GroupBiayaKuliahController');
    
    Route::resource('detail-biaya-kuliah','Keuangan\DetailBiayaKuliahController');
    Route::get('/set-detail-biaya/{id}','Keuangan\DetailBiayaKuliahController@index')->name('set-detail-biaya');
    Route::get('/list-details/{id}','Keuangan\DetailBiayaKuliahController@listDetail')->name('list-detail');
    Route::delete('/del-list-detail/{id}','Keuangan\DetailBiayaKuliahController@destroy')->name('del-detail');

    // Perkuliahan
    Route::resource('gol-kelas','Perkuliahan\GolKelasController');
    Route::resource('in-kelas','Perkuliahan\InKelasController');
    Route::get('/add-kelas/{id}','Perkuliahan\InKelasController@index')->name('in.kelas');
    Route::get('/add-kelas-mhs/{id}','Perkuliahan\InKelasController@listMahasiswa')->name('list.mahasiswa');
    Route::delete('/del-kelas-mhs/{id}','Perkuliahan\InKelasController@destroy')->name('del.mahasiswa');

    Route::resource('status-kelas-kuliah','Perkuliahan\StatusKelasKuliahController');
    Route::resource('karakter-matakuliah','Perkuliahan\KarakterMatakuliahController');
    Route::resource('buka-kelas','Perkuliahan\BukaKelasController');
});

resources/views/rsc/footer.blade.php
<!-- Footer -->
<footer class="content-footer footer bg-footer-theme">
    <div class="container-fluid d-flex flex-wrap justify-content-between py-2 flex-md-row flex-column">
    <div class="mb-2 mb-md-0">
        © <script>
        document.write(new Date().getFullYear())
        </script>
        - Developed by <a href="#" target="_blank" class="footer-link fw-semibold">Xiaonanhai</a>
    </div>
    <div>
        
        <a href="#" class="footer-link me-4" target="_blank">License</a>
        <a href="#" target="_blank" class="footer-link me-4">More Themes</a>
        
        <a href="#" target="_blank" class="footer-link me-4">Documentation</a>
        
        
        <a href="#" target="_blank" class="footer-link d-none d-sm-inline-block">Support</a>
        
    </div>
    </div>
</footer>
<!-- / Footer -->

resources/views/rsc/scripts.blade.php
    <!-- Bootstrap -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
    <script src="{{asset('template/plugins/jquery/jquery.min.js')}}"></script>
    <script src="https://code.jquery.com/ui/1.13.2/jquery-ui.js" integrity="sha256-xLD7nhI62fcsEZK2/v8LsBcb4lG7dgULkuXoXB/j91c=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.0.0-alpha1/js/bootstrap.bundle.min.js"></script>

    <!-- For Serverside Datatable -->
    <script src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.12.1/js/dataTables.bootstrap5.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.6.4/js/bootstrap-datepicker.js"></script>
    <script src="{{asset('assets/vendor/libs/sweetalert2/sweetalert2.js')}}" />
    @include('sweetalert::alert')

    <script src="https://cdnjs.cloudflare.com/ajax/libs/izitoast/1.4.0/js/iziToast.js"></script>

    <script src="{{asset('assets/vendor/js/helpers.js')}}"></script>

    <!--! Template customizer & Theme config files MUST be included after core stylesheets and helpers.js in the <head> section -->
    <!--? Template customizer: To hide customizer set displayCustomizer value false in config.js.  -->
    <script src="{{asset('assets/vendor/js/template-customizer.js')}}"></script>
    <!--? Config:  Mandatory theme config file contain global vars & default theme options, Set your preferred theme option in this file.  -->
    <script src="{{asset('assets/js/config.js')}}"></script>
        
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async="async" src="https://www.googletagmanager.com/gtag/js?id=GA_MEASUREMENT_ID"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
        dataLayer.push(arguments);
        }
        gtag('js', new Date());
        gtag('config', 'GA_MEASUREMENT_ID');
    </script>
    <!-- Custom notification for demo -->
    <!-- beautify ignore:end -->

    <!-- build:js assets/vendor/js/core.js -->
    
    <script src="{{asset('assets/vendor/libs/popper/popper.js')}}"></script>
    <script src="{{asset('assets/vendor/js/bootstrap.js')}}"></script>
    <script src="{{asset('assets/vendor/libs/perfect-scrollbar/perfect-scrollbar.js')}}"></script>
    <script src="{{asset('assets/vendor/libs/hammer/hammer.js')}}"></script>
    <script src="{{asset('assets/vendor/libs/i18n/i18n.js')}}"></script>
    <script src="{{asset('assets/vendor/libs/typeahead-js/typeahead.js')}}"></script>
    <script src="{{asset('assets/vendor/js/menu.js')}}"></script>
    <!-- endbuild -->

    <!-- Vendors JS -->
    <script src="{{asset('assets/vendor/libs/apex-charts/apexcharts.js')}}"></script>

    <!-- Main JS -->
    <script src="{{asset('assets/js/main.js')}}"></script>

    <!-- Page JS -->
    <script src="{{asset('assets/js/dashboards-analytics.js')}}"></script>
    <script src="https://momentjs.com/downloads/moment.js"></script>
    

resources/views/rsc/sidebar.blade.php
<!-- Menu -->
<aside id="layout-menu" class="layout-menu menu-vertical menu bg-menu-theme">

                
    <div class="app-brand demo mt-3">
    <a href="{{route('dashboard')}}" class="app-brand-link">
        <span class="app-brand-logo demo"><img src="{{asset('images/svg/Aanew.png')}}" width="32px" height="32px" alt=""></span>
        <span class="app-brand-text demo menu-text fw-bold ms-2">{{config('app.name')}}</span>
    </a>

    <a href="javascript:void(0);" class="layout-menu-toggle menu-link text-large ms-auto">
        <i class="bx menu-toggle-icon d-none d-xl-block fs-4 align-middle"></i>
        <i class="bx bx-x d-block d-xl-none bx-sm align-middle"></i>
    </a>
    </div>

    
    <div class="menu-divider mt-0  ">
    </div>

    <div class="menu-inner-shadow"></div>

    
    
    <ul class="menu-inner py-1">
    <!-- Dashboards -->
    <li class="menu-item">
        <a href="{{route('dashboard')}}" class="menu-link {{set_active('dashboard')}}">
        <i class="menu-icon tf-icons bx bx-home-circle bx-tada-hover"></i>
        <div data-i18n="Dashboards">Dashboards</div>
        </a>
    </li>

    <!-- Apps & Pages -->
    <li class="menu-header small text-uppercase"><span class="menu-header-text">Main Menus</span></li>
    <li class="menu-item">
        <a href="javascript:void(0);" class="menu-link menu-toggle {{set_active('gol-kelas.index')}}">
        <i class='menu-icon tf-icons bx bx-dock-top bx-tada-hover'></i>
        <div data-i18n="Perkuliahan">Perkuliahan</div>
        </a>
        <ul class="menu-sub">
        <li class="menu-item">
            <a href="{{route('gol-kelas.index')}}" class="menu-link {{set_active('gol-kelas.index')}}">
            <div data-i18n="Kelompok Mahasiswa">Kelompok Mahasiswa</div>
            </a>
        </li>
        <li class="menu-item">
            <a href="{{route('buka-kelas.index')}}" class="menu-link {{set_active('buka-kelas.index')}}">
            <div data-i18n="Buka Kelas (Satu)">Buka Kelas (Satu)</div>
            </a>
        </li>
        </ul>
    </li>
    <li class="menu-item">
        <a href="javascript:void(0);" class="menu-link menu-toggle {{set_active('periode.index')}} OR {{set_active('kurikulum.index')}} OR {{set_active('matakuliah.index')}} OR {{set_active('gol-matakuliah.index')}}">
        <i class='menu-icon tf-icons bx bx-buildings bx-tada-hover'></i>
        <div data-i18n="Universitas">Universitas</div>
        </a>
        <ul class="menu-sub">
        <li class="menu-item">
            <a href="{{route('periode.index')}}" class="menu-link {{set_active('periode.index')}}">
            <div data-i18n="Periode">Periode</div>
            </a>
        </li>
        <li class="menu-item">
            <a class="menu-link menu-toggle {{set_active('kurikulum.index')}} OR {{set_active('matakuliah.index')}} OR {{set_active('gol-matakuliah.index')}}" href="javascript:void(0)">
            <div data-i18n="Kurikulum">Kurikulum</div></a>
            <ul class="menu-sub">
                <li class="menu-item">
                    <a href="{{route('kurikulum.index')}}" class="menu-link {{set_active('kurikulum.index')}}">
                    <div data-i18n="Daftar Kurikulum">Daftar Kurikulum</div>
                    </a>
                </li>
                <li class="menu-item">
                    <a href="{{route('matakuliah.index')}}" class="menu-link {{set_active('matakuliah.index')}}">
                    <div data-i18n="Daftar Matakuliah">Daftar Matakuliah</div>
                    </a>
                </li>
                <li class="menu-item">
                    <a href="{{route('gol-matakuliah.index')}}" class="menu-link {{set_active('gol-matakuliah.index')}}">
                    <div data-i18n="Gol. Matakuliah">Gol. Matakuliah</div>
                    </a>
                </li> 
            </ul>
        </li>
             
        </ul>
    </li>
    <li class="menu-item">
        <a href="javascript:void(0);" class="menu-link menu-toggle {{set_active('pegawai.index')}} OR {{set_active('mahasiswa.index')}} OR {{set_active('status-pegawai.index')}} OR {{set_active('status-mahasiswa.index')}} OR {{set_active('api-mahasiswa.index')}} OR {{set_active('calon-mahasiswa.index')}}  OR {{set_active('api-mahasiswa-prodi.index')}} OR {{set_active('user.index')}}">
        <i class="menu-icon tf-icons bx bx-user bx-tada-hover"></i>
        <div data-i18n="Users">Users</div>
        </a>
        <ul class="menu-sub">
            <li class="menu-item">
                <a href="{{route('pegawai.index')}}" class="menu-link {{set_active('pegawai.index')}}">
                <div data-i18n="Pegawai">Pegawai</div>
                </a>
            </li>        
            <li class="menu-item">
                <a href="{{route('mahasiswa.index')}}" class="menu-link {{set_active('mahasiswa.index')}}">
                <div data-i18n="Mahasiswa">Mahasiswa</div>
                </a>
            </li>
            <li class="menu-item">
                <a href="{{route('status-pegawai.index')}}" class="menu-link {{set_active('status-pegawai.index')}}">
                <div data-i18n="Status Pegawai">Status Pegawai</div>
                </a>
            </li>               
            <li class="menu-item">
                <a href="{{route('status-mahasiswa.index')}}" class="menu-link {{set_active('status-mahasiswa.index')}}">
                <div data-i18n="Status Mahasiswa">Status Mahasiswa</div>
                </a>
            </li> 
            <li class="menu-item">
                <a href="javascript:void(0);" class="menu-link menu-toggle {{set_active('api-mahasiswa.index')}} OR {{set_active('calon-mahasiswa.index')}}  OR {{set_active('api-mahasiswa-prodi.index')}}">
                <div data-i18n="Data API">Data API</div>
                </a>
                <ul class="menu-sub">
                <li class="menu-item">
                    <a href="{{route('api-mahasiswa.index')}}" class="menu-link {{set_active('api-mahasiswa.index')}}">
                    <div data-i18n="All Mahasiswa">All Mahasiswa</div>
                    </a>
                </li>      
                </ul>
            </li>        
            <li class="menu-item">
                <a href="{{route('user.index')}}" class="menu-link {{set_active('user.index')}}">
                <div data-i18n="Administrator">Administrator</div>
                </a>
            </li>
        </ul>
    </li>
    
    <li class="menu-item">
        <a href="javascript:void(0);" class="menu-link menu-toggle {{set_active('jabatan.index')}} OR {{set_active('pendidik.index')}} OR {{set_active('jabatan-pegawai.index')}}">
        <i class='menu-icon tf-icons bx bx-briefcase-alt bx-tada-hover'></i>
        <div data-i18n="Jabatan">Jabatan</div>
        </a>
        <ul class="menu-sub">
            <li class="menu-item">
                <a href="{{route('jabatan.index')}}" class="menu-link {{set_active('jabatan.index')}}">
                <div data-i18n="Jabatan">Jabatan</div>
                </a>
            </li> 
            <li class="menu-item">
                <a href="{{route('pendidik.index')}}" class="menu-link {{set_active('pendidik.index')}}">
                <div data-i18n="Pendidik (Dosen)">Pendidik (Dosen)</div>
                </a>
            </li> 
            <li class="menu-item">
                <a href="{{route('jabatan-pegawai.index')}}" class="menu-link {{set_active('jabatan-pegawai.index')}}">
                <div data-i18n="Jabatan Pegawai">Jabatan Pegawai</div>
                </a>
            </li>       
                 
        </ul>
    </li>
    
    
    <li class="menu-item">
        <a href="javascript:void(0);" class="menu-link menu-toggle {{set_active('fakultas.index')}} OR {{set_active('prodi.index')}} OR {{set_active('data-formulir.index')}} OR {{set_active('status-kelas-kuliah.index')}} OR {{set_active('karakter-matakuliah.index')}}">
        <i class='menu-icon tf-icons bx bx-data bx-tada-hover'></i>
        <div data-i18n="Data Master">Data Master</div>
        </a>
        <ul class="menu-sub">
            <li class="menu-item">
                <a href="{{route('fakultas.index')}}" class="menu-link {{set_active('fakultas.index')}}">
                <div data-i18n="Daftar Fakultas">Daftar Fakultas</div>
                </a>
            </li>
            <li class="menu-item">
                <a href="{{route('prodi.index')}}" class="menu-link {{set_active('prodi.index')}}">
                <div data-i18n="Daftar Prodi">Daftar Prodi</div>
                </a>
            </li>  
            <li class="menu-item">
                <a href="{{route('data-formulir.index')}}" class="menu-link {{set_active('data-formulir.index')}}">
                <div data-i18n="Data Formulir">Data Formulir</div>
                </a>
            </li>      
            <li class="menu-item">
                <a href="{{route('status-kelas-kuliah.index')}}" class="menu-link {{set_active('status-kelas-kuliah.index')}}">
                <div data-i18n="Status Kelas Kuliah">Status Kelas Kuliah</div>
                </a>
            </li>      
            <li class="menu-item">
                <a href="{{route('karakter-matakuliah.index')}}" class="menu-link {{set_active('karakter-matakuliah.index')}}">
                <div data-i18n="Karakter Matakuliah">Karakter Matakuliah</div>
                </a>
            </li>      
        </ul>
    </li>
    

    <!-- Keuangan -->
    <li class="menu-header small text-uppercase"><span class="menu-header-text">Keuangan</span></li>
    <li class="menu-item">
        <a href="{{route('invoice.index')}}" class="menu-link {{set_active('invoice.index')}}">
        <i class="menu-icon tf-icons bx bx-receipt bx-tada-hover"></i>
        <div data-i18n="Invoice">Invoice</div>
        </a>
    </li>    
    <li class="menu-item">
        <a href="{{route('payment.index')}}" class="menu-link {{set_active('payment.index')}}">
        <i class="menu-icon tf-icons bx bx-money bx-tada-hover"></i>
        <div data-i18n="Payments">Payments</div>
        </a>
    </li>    
        
    <li class="menu-item">
        <a href="javascript:void(0);" class="menu-link menu-toggle {{set_active('biaya-kuliah.index')}} OR {{set_active('setup-biaya.index')}} OR {{set_active('custom-biaya.index')}}">
        <i class='menu-icon tf-icons bx bx-door-open bx-tada-hover'></i>
        <div data-i18n="Admission">Admission</div>
        </a>
        <ul class="menu-sub">
            <li class="menu-item">
                <a href="{{route('biaya-kuliah.index')}}" class="menu-link {{set_active('biaya-kuliah.index')}}">
                <div data-i18n="Tuition Fees">Tuition Fees</div>
                </a>
            </li>
            <li class="menu-item">
                <a href="{{route('custom-biaya.index')}}" class="menu-link {{set_active('custom-biaya.index')}}">
                <div data-i18n="Customize Cost">Customize Cost</div>
                </a>
            </li>
            <li class="menu-item">
                <a href="{{route('setup-biaya.index')}}" class="menu-link {{set_active('setup-biaya.index')}}">
                <div data-i18n="Setup Cost">Setup Cost</div>
                </a>
            </li>        
        </ul>
    </li>
    <li class="menu-item">
        <a href="javascript:void(0);" class="menu-link menu-toggle {{set_active('fines.index')}} OR {{set_active('g-biaya-kuliah.index')}} OR {{set_active('payment-list.index')}}">
        <i class='menu-icon tf-icons bx bx-data bx-tada-hover'></i>
        <div data-i18n="Data Master">Data Master</div>
        </a>
        <ul class="menu-sub">
            <li class="menu-item">
                <a href="{{route('fines.index')}}" class="menu-link {{set_active('fines.index')}}">
                <div data-i18n="Fines">Fines</div>
                </a>
            </li>
            <li class="menu-item">
                <a href="{{route('g-biaya-kuliah.index')}}" class="menu-link {{set_active('g-biaya-kuliah.index')}}">
                <div data-i18n="Group Tuition Fees">Group Tuition Fees</div>
                </a>
            </li>
            <li class="menu-item">
                <a href="{{route('payment-list.index')}}" class="menu-link {{set_active('payment-list.index')}}">
                <div data-i18n="Payment List">Payment List</div>
                </a>
            </li>
        </ul>
    </li>
    <!-- End of Sidebar Keuangan -->
    </ul>
    
    

</aside>
<!-- / Menu -->