routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth.login');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('dashboard');

Route::group(['middleware' => 'auth'], function(){
    Route::resource('prodi','Admin\ProdiController');
    Route::resource('kurikulum','Admin\KurikulumController');
    Route::resource('fakultas','Admin\FakultasController');
    Route::resource('periode','Admin\PeriodeController');
    Route::resource('matakuliah','Admin\MatakuliahController');
    Route::resource('mk-kurikulum','Admin\MatakuliahKurikulumController');
    Route::resource('user','Admin\UserController');
    Route::resource('data-formulir','Admin\DataFormulirController');
    Route::resource('pegawai','Admin\PegawaiController');
    Route::resource('jabatan','Admin\JabatanController');
    Route::resource('jabatan-pegawai','Admin\JabatanPegawaiController');
    Route::resource('pendidik','Admin\PendidikController');
    Route::resource('calon-mahasiswa','Admin\CalonMahasiswaController');
    Route::resource('gol-matakuliah','Admin\GolMatakuliahController');
    Route::resource('status-pegawai','Admin\StatusPegawaiController');
    Route::resource('status-mahasiswa','Admin\StatusMahasiswaController');
    Route::resource('mahasiswa','Admin\MahasiswaController');

    Route::post('archived-faculty','Admin\FakultasController@archiveFaculty')->name('archiveFaculty');
    Route::post('archived-kurikulum','Admin\KurikulumController@archiveKurikulum')->name('archiveKurikulum');
    Route::post('archived-matakuliah','Admin\MatakuliahController@archiveMatakuliah')->name('archiveMatakuliah');
    Route::post('archived-prodi','Admin\ProdiController@archiveProdi')->name('archiveProdi');
    Route::post('archived-data-formulir','Admin\DataFormulirController@archiveDataFormulir')->name('archiveDataFormulir');
    Route::post('archived-jabatan-pegawai','Admin\JabatanPegawaiController@archiveJabatanPegawai')->name('archiveJabatanPegawai');
    Route::post('archived-status-pegawai','Admin\StatusPegawaiController@archiveStatusPegawai')->name('archiveStatusPegawai');
    Route::post('archived-status-mahasiswa','Admin\StatusMahasiswaController@archiveStatusMahasiswa')->name('archiveStatusMahasiswa');

    Route::post('switch-period','Admin\PeriodeController@switchPeriode')->name('change-period-status');
    Route::post('switch-matakuliah','Admin\MatakuliahController@switchMatakuliah')->name('change-matakuliah-status');
    Route::post('switch-kurikulum','Admin\KurikulumController@switchKurikulum')->name('change-kurikulum-status');
    Route::get('matakuliah-view','Admin\MatakuliahController@view')->name('view-detail-matakuliah');
    Route::get('profile','Admin\UserController@profile')->name('profile');

    Route::get('change-password', 'Admin\UserController@getPass');
    Route::post('change-password', 'Admin\UserController@postPass')->name('change-password');

    Route::get('/add-matakuliah-kurikulum/{id}','Admin\MatakuliahKurikulumController@index')->name('setting.mkkurikulum');
    Route::get('/add-matakuliah-kurikulums/{id}','Admin\MatakuliahKurikulumController@listMK')->name('list.mkkurikulum');
    Route::delete('/del-matakuliah-kurikulum/{id}','Admin\MatakuliahKurikulumController@destroy')->name('del.mkkurikulum');

    Route::get('show-archived-matakuliah','Admin\MatakuliahController@show')->name('show.archived.matakuliah');
    Route::get('show-archived-kurikulum','Admin\KurikulumController@show')->name('show.archived.kurikulum');
    Route::get('show-archived-fakultas','Admin\FakultasController@show')->name('show.archived.fakultas');
    Route::get('show-archived-prodi','Admin\ProdiController@show')->name('show.archived.prodi');
    Route::get('show-archived-data-formulir','Admin\DataFormulirController@show')->name('show.archived.dataformulir');
    Route::get('show-archived-jabatan-pegawai','Admin\JabatanPegawaiController@show')->name('show.archived.jabatanpegawai');
    Route::get('show-archived-status-pegawai','Admin\StatusPegawaiController@show')->name('show.archived.status.pegawai');
    Route::get('show-archived-status-mahasiswa','Admin\StatusMahasiswaController@show')->name('show.archived.status.mahasiswa');
    
    Route::post('unarchived-matakuliah','Admin\MatakuliahController@unarchiveMatakuliah')->name('unarchiveMatakuliah');
    Route::post('unarchived-kurikulum','Admin\KurikulumController@unarchiveKurikulum')->name('unarchiveKurikulum');
    Route::post('unarchived-fakultas','Admin\FakultasController@unarchiveFakultas')->name('unarchiveFakultas');
    Route::post('unarchived-prodi','Admin\ProdiController@unarchiveProdi')->name('unarchiveProdi');
    Route::post('unarchived-data-formulir','Admin\DataFormulirController@unarchiveDataFormulir')->name('unarchiveDataFormulir');
    Route::post('unarchived-jabatan-pegawai','Admin\JabatanPegawaiController@unarchiveJabatanPegawai')->name('unarchiveJabatanPegawai');
    Route::post('unarchived-status-pegawai','Admin\StatusPegawaiController@unarchiveStatusPegawai')->name('unarchiveStatusPegawai');
    Route::post('unarchived-status-mahasiswa','Admin\StatusMahasiswaController@unarchiveStatusMahasiswa')->name('unarchiveStatusMahasiswa');

    Route::get('mahasiswa-view','Admin\CalonMahasiswaController@view')->name('view-detail-mahasiswa');

    // API Mahasiswa
    Route::get('/mahasiswa/tahun','Admin\CalonMahasiswaController@show')->name('get.mahasiswa');
    Route::get('mahasiswa-view','Admin\CalonMahasiswaController@view')->name('view-detail-mahasiswa');
    Route::get('datatable-mahasiswa','Admin\CalonMahasiswaController@showDataTable')->name('datatable-mahasiswa');
    
    Route::resource('api-mahasiswa', 'Admin\ApiMahasiswaController');
    Route::get('api-mahasiswa-view','Admin\ApiMahasiswaController@viewformdetail')->name('view-detail-form');
    Route::resource('api-mahasiswa-prodi', 'Admin\ApiMahasiswaProdiController');
    Route::get('datatable-mahasiswa-prodi','Admin\ApiMahasiswaProdiController@showDataTable')->name('datatable-mahasiswa-prodi');

    // Keuangan
    Route::resource('payment-list','Keuangan\PaymentListController');
    Route::resource('payment','Keuangan\PaymentController');
    Route::get('/view-rincian-payment/{id}','Keuangan\ViewRincianPaymentController@index')->name('view-rincian-payment');
    Route::get('/rincian-payment/{id}','Keuangan\ViewRincianPaymentController@index')->name('list-rincian-payment');
    Route::get('/view-rincian-payment/payment/{id}/edit','Keuangan\PaymentController@edit');
    Route::delete('/view-rincian-payment/payment/{id}','Keuangan\PaymentController@destroy');

    Route::get('print-payment','Keuangan\PaymentController@print')->name('print-payment');
    Route::post('add-potongan','Keuangan\ViewRincianPaymentController@addPotongan')->name('add-potongan');

    Route::post('import-payment', 'Keuangan\PaymentController@importPayment')->name('import-payment');
    Route::get('count-fine','Keuangan\PaymentController@countFine')->name('count-fine');

    Route::resource('setup-biaya','Keuangan\SetupBiayaController');
    Route::resource('biaya-kuliah','Keuangan\BiayaKuliahController');

    Route::resource('custom-biaya','Keuangan\CustomBiayaController');
    Route::post('switch-custom-biaya','Keuangan\CustomBiayaController@switchStatus')->name('change-custom-biaya-status');

    Route::resource('discount-biaya','Keuangan\DiscountBiayaController');
    Route::get('/potongan-biaya/{id}','Keuangan\DiscountBiayaController@index')->name('potongan-biaya');
    Route::get('/list-discounts/{id}','Keuangan\DiscountBiayaController@listDiscount')->name('list-discount');
    Route::delete('/del-list-discount/{id}','Keuangan\DiscountBiayaController@destroy')->name('del-discount');
    Route::post('import-biaya-kuliah', 'Keuangan\BiayaKuliahController@importBiayaKuliah')->name('import-biaya-kuliah');
    
    Route::post('search-payment-history', 'Keuangan\ViewRincianPaymentController@searchPaymentHistory')->name('search-payment-history');
    
    Route::resource('fines','Keuangan\FineController');
    Route::resource('invoice','Keuangan\InvoiceController');
    Route::post('import-invoice', 'Keuangan\InvoiceController@importInvoice')->name('import-invoice');

    Route::resource('g-biaya-kuliah','Keuangan\GroupBiayaKuliahController');
    
    Route::resource('detail-biaya-kuliah','Keuangan\DetailBiayaKuliahController');
    Route::get('/set-detail-biaya/{id}','Keuangan\DetailBiayaKuliahController@index')->name('set-detail-biaya');
    Route::get('/list-details/{id}','Keuangan\DetailBiayaKuliahController@listDetail')->name('list-detail');
    Route::delete('/del-list-detail/{id}','Keuangan\DetailBiayaKuliahController@destroy')->name('del-detail');

    // Perkuliahan
    Route::resource('gol-kelas','Perkuliahan\GolKelasController');
    Route::resource('in-kelas','Perkuliahan\InKelasController');
    Route::get('/add-kelas/{id}','Perkuliahan\InKelasController@index')->name('in.kelas');
    Route::get('/add-kelas-mhs/{id}','Perkuliahan\InKelasController@listMahasiswa')->name('list.mahasiswa');
    Route::delete('/del-kelas-mhs/{id}','Perkuliahan\InKelasController@destroy')->name('del.mahasiswa');

    Route::resource('status-kelas-kuliah','Perkuliahan\StatusKelasKuliahController');
    Route::resource('karakter-matakuliah','Perkuliahan\KarakterMatakuliahController');
    Route::resource('buka-kelas','Perkuliahan\BukaKelasController');
});

app/Http/Controllers/Perkuliahan/BukaKelasController.php
<?php

namespace App\Http\Controllers\Perkuliahan;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Perkuliahan\StatusKelasKuliah;
use App\Model\Matakuliah;
use App\Model\Periode;
use App\Model\Prodi;
use Response;
use Session;
use Validator;
use Auth;

class BukaKelasController extends Controller
{
    public function index(Request $request)
    {
        $getPeriode = Periode::all();
        $getStatusKelas = StatusKelasKuliah::all();
        $getProdi = Prodi::all();
        $getMatakuliah = Matakuliah::all();
        return view('perkuliahan.buka-kelas.index', compact('getPeriode','getStatusKelas','getProdi','getMatakuliah'));
    }
}

app/Http/Controllers/Perkuliahan/GolKelasController.php
<?php

namespace App\Http\Controllers\Perkuliahan;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Perkuliahan\GolKelas;
use App\Model\Periode;
use Response;
use Session;
use Validator;
use Auth;

class GolKelasController extends Controller
{
    public function index(Request $request)
    {
        $getData = GolKelas::leftJoin('periodes','periodes.id','=','gol_kelas.id_periode')
            ->select('gol_kelas.id AS id','gol_kelas.*','periodes.nama_periode')
            ->get();
                
        if($request->ajax()){
            return datatables()->of($getData)
                ->addColumn('action', function($data){
                        $button = '<a href="javascript:void(0)" data-toggle="tooltip" data-placement="bottom" title="Edit" data-id="'.$data->id.'" data-original-title="Edit" class="edit btn btn-success btn-xs edit-post"><i class="bx bx-xs bx-edit"></i></a>';
                        $button .= '&nbsp;&nbsp;';
                        $button .= '<button type="button" name="delete" id="'.$data->id.'" class="delete btn btn-danger btn-xs" data-toggle="tooltip" data-placement="bottom" title="Delete"><i class="bx bx-xs bx-trash"></i></button>';
                        return $button;
                })->addColumn('setting', function($data){
                    return '<a href="'.Route('in.kelas',['id' => $data->id]).'" name="setting" class="dropdown-shortcuts-add text-body setting" data-id="'.$data->id.'" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Add Class"><span class="badge bg-label-primary me-1"><i class="bx bx-xs bx-plus-circle"></i> '.$data->nama_golongan.'</span></a>';
                })
                ->rawColumns(['action','setting'])
                ->addIndexColumn(true)
                ->make(true);
        }
        $getPeriode = Periode::where('is_active','=',1)->get();
        return view('perkuliahan.gol-kelas.index', compact('getPeriode'));
    }

    public function store(Request $request)
    {
        $request->validate([
            'nama_golongan' => 'required',
            'keterangan'    => 'required',
            'id_periode'    => 'required',
        ],[
            'nama_golongan.required' => 'Anda belum menginputkan nama golongan',
            'keterangan.required'    => 'Anda belum menginputkan keterangan',
            'id_periode.required'    => 'Anda belum memilih periode'
        ]);

        $post = GolKelas::updateOrCreate(['id' => $request->id],
                [
                    'nama_golongan' => $request->nama_golongan,
                    'id_periode'    => $request->id_periode,
                    'keterangan'    => $request->keterangan,
                    'is_archived'   => 0,
                ]); 

        return response()->json($post);
    }

    public function edit($id)
    {
        $where = array('id' => $id);
        $post  = GolKelas::where($where)->first();
     
        return response()->json($post);
    }

    public function destroy($id)
    {
        $post = GolKelas::where('id',$id)->delete();     
        return response()->json($post);
    }
}

app/Http/Controllers/Perkuliahan/InKelasController.php
<?php

namespace App\Http\Controllers\Perkuliahan;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Model\Prodi;
use App\Model\Periode;
use Response;
use Session;
use Validator;
use Auth;
use DB;

class InKelasController extends Controller
{
    public function index(Request $request, $id)
    {
        $dataKelas = DB::table('gol_mahasiswas')->leftJoin('mahasiswas','mahasiswas.nim','=','gol_mahasiswas.nim')
            ->leftJoin('gol_kelas','gol_kelas.id','=','gol_mahasiswas.id_golongan')
            ->leftJoin('periodes','periodes.id','=','gol_kelas.id_periode')
            ->leftJoin('status_mahasiswas','status_mahasiswas.id','=','mahasiswas.id_status_Mahasiswa')
            ->select('gol_mahasiswas.id AS id','gol_mahasiswas.*','mahasiswas.nama_mahasiswa','nama_status','gol_kelas.nama_golongan','periodes.nama_periode')
            ->where('gol_mahasiswas.id_golongan','=',$id)
            ->get();
        if($request->ajax()){
            return datatables()->of($dataKelas)
                ->addColumn('action', function($data){
                       return '<button type="button" name="delete" id="'.$data->id.'" class="delete btn btn-danger btn-xs" data-toggle="tooltip" data-placement="bottom" title="Delete"><i class="bx bx-xs bx-trash"></i></button>';
                })
                ->rawColumns(['action'])
                ->addIndexColumn(true)
                ->make(true);
        }
        $getInfo = DB::table('gol_kelas')->leftJoin('periodes','periodes.id','=','gol_kelas.id_periode')
            ->select('gol_kelas.id AS id','gol_kelas.*','periodes.nama_periode')
            ->where('gol_kelas.id',$id)
            ->get();
        $getGolKelas = DB::table('gol_kelas')->where('id','!=',$id)->get();
        $getPeriode = Periode::all();
        $getProdi = Prodi::all();
        return view('perkuliahan.add-kelas.index',['id' => $id,'dataKelas' => $dataKelas,'getInfo' => $getInfo,'getGolKelas' => $getGolKelas,'getPeriode' => $getPeriode, 'getProdi' => $getProdi]);
    }

    public function listMahasiswa(Request $request, $id)
    {
        $dataKelas = DB::table('gol_mahasiswas')->leftJoin('mahasiswas','mahasiswas.nim','=','gol_mahasiswas.nim')
            ->leftJoin('gol_kelas','gol_kelas.id','=','gol_mahasiswas.id_golongan')
            ->leftJoin('periodes','periodes.id','=','gol_kelas.id_periode')
            ->leftJoin('status_mahasiswas','status_mahasiswas.id','=','mahasiswas.id_status_Mahasiswa')
            ->select('gol_mahasiswas.id AS id','gol_mahasiswas.*','mahasiswas.nama_mahasiswa','nama_status','gol_kelas.nama_golongan','periodes.nama_periode')
            ->where('gol_mahasiswas.id_golongan','=',$id)
            ->get();
        if($request->ajax()){
            return datatables()->of($dataKelas)
                ->addColumn('action', function($data){
                       return '<button type="button" name="delete" id="'.$data->id.'" class="delete btn btn-danger btn-xs" data-toggle="tooltip" data-placement="bottom" title="Delete"><i class="bx bx-xs bx-trash"></i></button>';
                })
                ->rawColumns(['action'])
                ->addIndexColumn(true)
                ->make(true);
        }
        $getProdi = Prodi::all();
        return view('perkuliahan.add-kelas.index',['id' => $id,'dataKelas' => $dataKelas,'getProdi' => $getProdi]);
    }

    public function destroy($id)
    {
        $post = DB::table('gol_mahasiswas')->where('id',$id)->delete();     
        return response()->json($post);
    }
}

resources/views/perkuliahan/karakter-matakuliah/index.blade.php
@extends('layouts.backend')
@section('title','Karakter Matakuliah')

@section('breadcrumbs')
<div class="container">
<nav aria-label="breadcrumb mb-0">
    <ol class="breadcrumb breadcrumb-style2">
      <li class="breadcrumb-item">
        <a href="{{route('dashboard')}}">Home</a>
      </li>
      <li class="breadcrumb-item">
        <a href="{{route('karakter-matakuliah.index')}}">@yield('title')</a>
      </li>
      <li class="breadcrumb-item active">Data</li>
    </ol>
</nav>
</div>
@endsection

@section('content')

<div class="container flex-grow-1">
    <section id="basic-datatable">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-body">
                        <!-- MULAI TOMBOL TAMBAH -->
                        <div class="mb-3">
                            <a href="javascript:void(0)" class="dropdown-shortcuts-add text-body" id="tombol-tambah" data-bs-toggle="tooltip" data-bs-placement="top" title="Add data"><i class="bx bx-sm bx-plus-circle bx-spin-hover"></i></a>
                        </div>
                        
                        <!-- AKHIR TOMBOL -->
                            <table class="table table-hover table-responsive" id="table_karakter_matakuliah">
                              <thead>
                                <tr>
                                  <th>#</th>
                                  <th>Name</th>
                                  <th>Notes</th>
                                  <th>Period</th>
                                  <th>Actions</th>
                                </tr>
                              </thead>
                            </table>
                        </div>
                    </div>

                    <!-- MULAI MODAL FORM TAMBAH/EDIT-->
                    <div class="modal fade" id="tambah-edit-modal" aria-hidden="true">
                        <div class="modal-dialog ">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="modal-judul"></h5>
                                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                </div>
                                <div class="modal-body">
                                    <form id="form-tambah-edit" name="form-tambah-edit" class="form-horizontal">
                                        <div class="row">
                                            <div class="col-sm-12">

                                                <input type="hidden" name="id" id="id">

                                                <div class="mb-3">
                                                    <label for="nama_karakter" class="form-label">Nama Karakter*</label>
                                                    <input type="text" class="form-control" id="nama_karakter" name="nama_karakter" value="" placeholder="Input Nama Karakter" />
                                                    <span class="text-danger" id="namaKarakterErrorMsg"></span>
                                                </div>

                                                <div class="mb-3">
                                                    <label for="keterangan" class="form-label">Keterangan</label>
                                                    <textarea class="form-control" id="keterangan" name="keterangan" rows="3"></textarea>
                                                    <span class="text-danger" id="keteranganErrorMsg"></span>
                                                </div>

                                                <div class="mb-3">
                                                    <label for="id_periode" class="form-label">Year Period*</label>
                                                    <select class="form-select" id="id_periode" name="id_periode" aria-label="Default select example" style="cursor:pointer;">
                                                        <option value="">- Choose -</option>
                                                        @foreach($getPeriode as $data)
                                                        <option value="{{$data->id}}">{{$data->nama_periode}}</option>
                                                        @endforeach
                                                    </select>
                                                    <span class="text-danger" id="idPeriodeErrorMsg"></span>
                                                </div>
                                                
                                            </div>
                                            <div class="col-sm-offset-2 col-sm-12">
                                                <hr class="mt-2">
                                                <div class="float-sm-end">
                                                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                                    <button type="submit" class="btn btn-primary btn-block" id="tombol-simpan" value="create">Save</button>
                                                </div>
                                            </div>
                                        </div>

                                    </form>
                                </div>
                                <div class="modal-footer">
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- AKHIR MODAL -->
                    
                </div>
            </div>
        </div>
    </section>
</div>

@endsection
@section('script')

<script>
    $(document).ready(function () {
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });
    });

    // DATATABLE
    $(document).ready(function () {
        var table = $('#table_karakter_matakuliah').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('karakter-matakuliah.index') }}",
            columns: [
                {data: null,sortable:false,
                    render: function (data, type, row, meta) {
                    return meta.row + meta.settings._iDisplayStart + 1;
                    }
                }, 
                {data: 'nama_karakter',name: 'nama_karakter'},
                {data: 'keterangan',name: 'keterangan'},
                {data: 'nama_periode',name: 'nama_periode'},
                {data: 'action',name: 'action'},
            ]
        });
    });

    //TOMBOL TAMBAH DATA
    $('#tombol-tambah').click(function () {
        $('#button-simpan').val("create-post");
        $('#id').val('');
        $('#form-tambah-edit').trigger("reset");
        $('#modal-judul').html("Add new data");
        $('#tambah-edit-modal').modal('show');
    });

    // TOMBOL TAMBAH
    if ($("#form-tambah-edit").length > 0) {
        $("#form-tambah-edit").validate({
            submitHandler: function (form) {
                var actionType = $('#tombol-simpan').val();
                $('#tombol-simpan').html('Saving..');

                $.ajax({
                    data: $('#form-tambah-edit').serialize(), 
                    url: "{{ route('karakter-matakuliah.store') }}",
                    type: "POST",
                    dataType: 'json',
                    success: function (data) {
                        $('#form-tambah-edit').trigger("reset");
                        $('#tambah-edit-modal').modal('hide');
                        $('#tombol-simpan').html('Save');
                        $('#table_karakter_matakuliah').DataTable().ajax.reload(null, true);
                        Swal.fire({
                            title: 'Good job!',
                            text: 'Data saved successfully!',
                            type: 'success',
                            customClass: {
                            confirmButton: 'btn btn-primary'
                            },
                            buttonsStyling: false,
                            timer: 2000
                        })
                    },
                    error: function(response) {
                        $('#namaKarakterErrorMsg').text(response.responseJSON.errors.nama_karakter);
                        $('#keteranganErrorMsg').text(response.responseJSON.errors.keterangan);
                        $('#idPeriodeErrorMsg').text(response.responseJSON.errors.id_periode);
                        $('#tombol-simpan').html('Save');
                        Swal.fire({
                            title: 'Error!',
                            text: 'Data failed to save!',
                            type: 'error',
                            customClass: {
                            confirmButton: 'btn btn-primary'
                            },
                            buttonsStyling: false,
                            timer: 2000
                        })
                    }
                });
            }
        })
    }

    // EDIT DATA
    $('body').on('click', '.edit-post', function () {
        var data_id = $(this).data('id');
        $.get('karakter-matakuliah/' + data_id + '/edit', function (data) {
            $('#modal-judul').html("Edit data");
            $('#tombol-simpan').val("edit-post");
            $('#tambah-edit-modal').modal('show');
              
            $('#id').val(data.id);
            $('#nama_karakter').val(data.nama_karakter);
            $('#keterangan').val(data.keterangan);
            $('#id_periode').val(data.id_periode);
        })
    });

    // TOMBOL DELETE
    $(document).on('click', '.delete', function () {
        dataId = $(this).attr('id');
        Swal.fire({
            title: 'Are you sure?',
            text: "It will be deleted permanently!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Yes, delete it!',
            showLoaderOnConfirm: true,
            preConfirm: function() {
                return new Promise(function(resolve) {
                    $.ajax({
                        url: "karakter-matakuliah/" + dataId,
                        type: 'DELETE',
                        data: {id:dataId},
                        dataType: 'json'
                    }).done(function(response) {
                        Swal.fire({
                            title: 'Deleted!',
                            text: 'Your data has been deleted.',
                            type: 'success',
                            timer: 2000
                        })
                        $('#table_karakter_matakuliah').DataTable().ajax.reload(null, true);
                    }).fail(function() {
                        Swal.fire({
                            title: 'Oops!',
                            text: 'Something went wrong with ajax!',
                            type: 'error',
                            timer: 2000
                        })
                    });
                });
            },
        });
    });

    function onlyNumeric(event) {
        var angka = (event.which) ? event.which : event.keyCode
        if (angka != 46 && angka > 31 && (angka < 48 || angka > 57))
            return false;
        return true;
    }

</script>

@endsection